# Generated by Django 5.1.7 on 2025-03-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employ_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
